services:
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./cert/ssl:/ssl
      - ./nginx-reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
  front:
    image: announce-front:1.00
    depends_on:
     - reverse-proxy
    volumes:
     - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf
     - ./announcement-frontend/dist/:/front-app/dist/
    build:
     context: ./announcement-frontend/
     dockerfile: Dockerfile
    expose:
     - "80"
  back:
    image: announce-back:1.00
#    volumes: 
#    - ./announcement-backend/target/:/app/
    depends_on:
     - reverse-proxy
     - database
    build:
     context: ./announcement-backend/
     dockerfile: Dockerfile
    environment:
     - MYSQL_USER=root
     - MYSQL_PASSWORD=RewLegendary123SuperDB!
     - MYSQL_DATABASE=announcement
     - MYSQL_PORT=3306
     - MYSQL_URL=database
     - PORT=8080
    expose:
     - "8080"
  database:
    image: mysql:8.0.32
    volumes:
     - ./announcement-databased/db-script.sql:/docker-entrypoint-initdb.d/db-script.sql
     - ./announcement-databased/data:/var/lib/mysql
    environment:
     - LANG="en_US.UTF-8"
     - TZ="UTC"
     - MYSQL_DATABASE=announcement
     - MYSQL_ROOT_PASSWORD=RewLegendary123SuperDB!
    ports:
     - "3306:3306"
networks: 
  default:
    name: app-announcement
    external: true
